### ISSUE TITLE
Wrong setname in "Gallop - Armed Police Unit (Japan)" ?

### ISSUE THREAD

**Issue by ojaksch** [wickerwaka/Arcade_m72#12]
You set the *setname* to *cosmccop*, but according to MAME's ROM list it should be *gallop*:

``
gallop            "Gallop - Armed Police Unit (Japan, M72 hardware)"
``
``
cosmccop          "Cosmic Cop (World)"
``

Or am I in a wrong assumption?

**Comment by birdybro** [comment]
This is correct. Technically `gallop` is the setname and `cosmccop` is the parent. If someone used an unmerged set the current MRA wouldn't work either. I'll fix it in a jiffy.

**Comment by ojaksch** [comment]
Perfect, thanks a lot! Our tty displays will be happy again then :)
