### ISSUE TITLE
57/60hz artifacting 

### ISSUE THREAD

**Issue by InsertDiskTwo** [wickerwaka/Arcade_m72#14]
I am testing RType and GALLOP Armed Police at 57hz and 60hz but it seems there is some weird flickering going on when scrolling. I am using VRR.

Very visible when using Sony Trinitron Preset.

Update - it seems to happen for all games in this core

**Comment by wickerwaka** [comment]
Just noting for future reference that you tracked this down to gamma causing the issue. In 57hz and 60hz modes, ce_pixel isn't quite 1/4 of the video clock, which gamma requires.

**Comment by InsertDiskTwo** [comment]
Glad to be of help!

**Comment by wickerwaka** [comment]
Fixed in official repo by this commit: https://github.com/MiSTer-devel/Arcade-IremM72_MiSTer/commit/77078fc80ad19a28d3eedc97b009f449b2784fac
