### ISSUE TITLE
Gallop continue dip flipped

### ISSUE THREAD

**Issue by oranki** [wickerwaka/Arcade_m72#16]
Gallop - Armed Police Unit has DIP switch "allow continue", but it's function is opposite to what it's set to. "No" allows continue, "Yes" does not.

**Comment by wickerwaka** [comment]
Fixed in official repo with this commit: https://github.com/MiSTer-devel/Arcade-IremM72_MiSTer/commit/8f2798cd68d5b62aa01e5154f4dba214b11c0d5f
